version: '3'
services:
  tf:
    build: ./
    image: contino/terraform
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app
    env_file: .env

  self_healing_function:
    build:
      context: ./self_healing_function
    init: true
    volumes:
      - './self_healing_function/src:/app/src'
    env_file: .env
    environment:
      - GITHUB_USERNAME=liam-johnston
      - GITHUB_TOKEN_SECRET_NAME=liamjohnston/node-weather-app/github-workflow-access-token

  self_healing_function_build:
    extends:
      service: self_healing_function
    working_dir: /app/dist
    volumes:
      - './dist:/app/dist'
