name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/**'
      - '*dockerfile'
      - 'modules/**'
      - '**.tf'
      - 'self_healing_function/**'
jobs:

  build_self_healing_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Functon
        run: make build_self_heal
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: self_healing_function
          path: dist

  tf_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_github_access_token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Run Terraform Plan
      run: make run_plan

  tf_apply:
    needs:
      - tf_plan
      - build_self_healing_function
    environment:
      name: approval
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_github_access_token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Download Self Healing Function
      uses: actions/download-artifact@v2
      with:
        name: self_healing_function
        path: ./dist
    - name: Terraform_Plan
      run: make run_plan
    - name: Run Terraform Apply
      run: make run_apply
